"""empty message

Revision ID: 1f3b8b027c11
Revises: 0763d677d453
Create Date: 2025-09-06 16:36:33.969702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3b8b027c11'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courtfile')
    # ### end Alembic commands ###
